# -*- coding: utf-8 -*-
"""Mayank_L_Surana_Cars_EDA_Project2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J67l0QVtAolh-EJusHBMK1qrp04lbE6Y

##Import the libraries
"""

import pandas as pd  #loading and manipulating our dataset
import numpy as np   #numerical operations
import matplotlib.pyplot as plt    #Creating Charts
import seaborn as sns

"""##Uploading the Dataset"""

from google.colab import files
uploaded = files.upload()

"""##Load the dataset"""

df = pd.read_csv('/content/Cars_Dataset.csv')
df

df.head()   #this will show me the first 5 rows and all the N columns

"""##Checking the Structure of the Datasset"""

df.shape

"""##Checking all the Columns"""

df.columns    #To get the list of all the columns

"""##Complete Information regarding the Dataset"""

df.info()

"""##Check the dataset statistically"""

df.describe(include="object")    #for inspecting the categorical variables.

"""##Data Quality Check"""

df.isnull().sum()

"""##Checking for Duplicates"""

df.duplicated().sum()

df[df.isnull().any(axis=1)]  #this shows which row is actually having the missing values

missing_values = df.isnull().sum()   #We store it in a variable
missing_values = missing_values[missing_values > 0]
missing_values

missing_percentage = (df.isnull().sum() / len(df)) * 100   #This tells us how must data is missing w.r.t all the rows
missing_percentage = missing_percentage[missing_percentage > 0]
missing_percentage

df[df.duplicated(keep=False)].sort_values(by="car_ID")

"""##Check categorical consistency"""

categorical_columns = df.select_dtypes(include=object).columns   #for the Object DATA type
categorical_columns

for column in categorical_columns:
  print(f"\n--- {column} ---")
  print(df[column].value_counts(dropna=False))

before_cleaning = df.shape
print("Rows before cleaning:", before_cleaning[0])
print("Columns before cleaning:", before_cleaning[1])

"""##Now Eliminating the Duplicate Rows"""

print('Before removing the Duplicates',df.shape)
df = df.drop_duplicates()
print('After removing the Duplicates',df.shape)  #We can Clearly see that - 5 rows are removed whereas there are No duplicate Columns

"""##Handle missing values"""

df.isnull().sum()  #Clearly we can see that ['fueltype','enginesize','horsepower','price']  has the null Values

#Handle missing values in numerical columns
numerical_missing = ["horsepower", "price", "enginesize"]

for column in numerical_missing:
    df.loc[:, column] = df[column].fillna(df[column].median())


#Handle missing value in categorical column
df.loc[:, "fueltype"] = df["fueltype"].fillna(df["fueltype"].mode()[0])

rows_after = df.shape[0]

print("\nDATA CLEANING - AFTER")
print("Rows:", rows_after)
print("Columns:", df.shape[1])
print("Missing cells:", df.isnull().sum().sum())  #By now we have removed all the missing cells
print("Duplicate rows:", df.duplicated().sum())   #By no we have removed all the duplicated rows

"""##Displaying Numerical and Categorical Variables"""

numerical_columns = df.select_dtypes(include=np.number).columns
categorical_columns = df.select_dtypes(include=object).columns

print("Numerical columns:")
print(numerical_columns)
print("\nCategorical columns:")
print(categorical_columns)

df.dtypes

"""##Descriptive Statistics"""

display(df[numerical_columns].describe())
display(df[categorical_columns].describe())

print("Mean price:", df["price"].mean())   #Statastical data for better graph plots for price
print("Median price:", df["price"].median())
print("Minimum price:", df["price"].min())
print("Maximum price:", df["price"].max())
print("Standard deviation:", df["price"].std())

"""##Univariate Analysis

###Histogram Plot
"""

plt.figure(figsize=(10, 5))

sns.histplot(data=df, x="price", bins=20, kde=True)  #to create a histogram.  #Bins divide range of prices into approximately 20 intervals/groups.

plt.title("Distribution of Car Prices")
plt.xlabel("Price")
plt.ylabel("Number of Cars")

plt.show()

"""###Count Plot"""

plt.figure(figsize=(4, 4))

sns.countplot(data=df, x="fueltype")

plt.title("Distribution of Cars by Fuel Type")
plt.xlabel("Fuel Type")
plt.ylabel("Number of Cars")

plt.show()

"""###Histogram Plot"""

plt.figure(figsize=(10, 6))

sns.histplot(data=df, x="horsepower", bins=20, kde=True)

plt.title("Distribution of Car Horsepower")
plt.xlabel("Horsepower")
plt.ylabel("Number of Cars")

plt.show()

"""##Bivariate Analysis

###Scatter Plot
"""

plt.figure(figsize=(10, 6))

sns.scatterplot(
    data=df,x="horsepower",y="price",color="green")

plt.title("Car Price vs Horsepower")
plt.xlabel("Horsepower")
plt.ylabel("Price")

plt.show()

"""###Scatter Plot"""

plt.figure(figsize=(10,6))
sns.scatterplot(data=df,x="enginesize",y="price",color="red")
plt.title("Car Price vs Engine Size")
plt.xlabel("Engine Size")
plt.ylabel("Price")
plt.show()

"""###Box Plot"""

plt.figure(figsize=(10, 6))

sns.boxplot(data=df,x="fueltype",y="price")

plt.title("Car Price Distribution by Fuel Type")
plt.xlabel("Fuel Type")
plt.ylabel("Price")

plt.show()

"""##Multivariate Analysis"""

plt.figure(figsize=(10,7))
correlation = df[numerical_columns].corr()
sns.heatmap(
    correlation,   ##For Multiple variables we Use Corelation Heatmap
    annot=True,cmap="coolwarm",fmt=".1f")

plt.title("Correlation Heatmap of Car Features")
plt.show()

"""##Outlier Analysis"""

plt.figure(figsize=(10, 5))

sns.boxplot(
    data=df,
    x="price",
    color="steelblue"
)

plt.title("Box Plot of Car Prices")
plt.xlabel("Price")

plt.show()

