# -*- coding: utf-8 -*-
"""Mayank_L_Surana_Logistic_Regression_Project_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZmrIpoc-lxxhOneFXen7QXYdIV8uxYKI

# Diabetes Prediction using Logistic Regression
### Pima Indians Diabetes Dataset

**Name:** Mayank L Surana  
**Date:** 04 October 2026   
**Batch:** A

##Import Libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (accuracy_score, precision_score, recall_score, f1_score,
                             roc_auc_score, confusion_matrix, ConfusionMatrixDisplay,
                             RocCurveDisplay, classification_report)

sns.set_style("whitegrid")

"""##Loading the Dataset"""

df = pd.read_csv('/content/diabetes.csv')

df.head()

"""##Dataset Shape"""

print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

"""##Listing out all the Column Names"""

print(df.columns.tolist(), sep='\n')

"""##Information regarding the Dataset"""

df.info()

"""##Statistical Summary"""

df.describe()  #Gives is the mean,count, Min.. etc,..

"""##Check Missing Values"""

df.isnull().sum()

"""##Identifying & replacing Invalid Zeroes"""

cols_with_invalid_zeros = ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]

print("Zeros BEFORE replacement:")
print((df[cols_with_invalid_zeros] == 0).sum())

df[cols_with_invalid_zeros] = df[cols_with_invalid_zeros].replace(0, np.nan)

print("\nMissing values AFTER replacement:")
print(df.isnull().sum())

"""#Exploratory visuals (the graphs the checklist wants visible)

## Class distribution
"""

plt.figure(figsize=(5, 4))
sns.countplot(x="Outcome", data=df)
plt.title("Class Distribution (0 = No diabetes, 1 = Diabetes)")
plt.show()

"""##Feature Distribution"""

# Feature distributions
df.hist(figsize=(12, 9), bins=20)
plt.suptitle("Feature Distributions", y=1.02)
plt.tight_layout()
plt.show()

"""##Co relation Heatmap"""

# Correlation heatmap
plt.figure(figsize=(9, 7))
sns.heatmap(df.corr(), annot=True, fmt=".2f", cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

"""##Train-test split"""

X = df.drop("Outcome", axis=1)
y = df["Outcome"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Train:", X_train.shape, "| Test:", X_test.shape)

"""##Building and training the model"""

model = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
    ("logreg", LogisticRegression(class_weight="balanced", max_iter=1000, random_state=42))
])

model.fit(X_train, y_train)
print("Model trained successfully")

"""##Evaluate the accuracy, precision"""

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

metrics = pd.DataFrame({
    "Metric": ["Accuracy", "Precision", "Recall", "F1-score", "ROC-AUC"],
    "Result": [accuracy_score(y_test, y_pred),
               precision_score(y_test, y_pred),
               recall_score(y_test, y_pred),
               f1_score(y_test, y_pred),
               roc_auc_score(y_test, y_prob)],
    "Meaning": ["Overall correct predictions",
                "Reliability of positive predictions",
                "Actual positive cases detected",
                "Balance of precision and recall",
                "Overall class-separation ability"]
})
metrics["Result"] = metrics["Result"].round(3)
display(metrics)

print(classification_report(y_test, y_pred, target_names=["No diabetes", "Diabetes"]))

"""##Confusion matrix and ROC curve"""

cm = confusion_matrix(y_test, y_pred)
tn, fp, fn, tp = cm.ravel()
print(f"TN = {tn} | FP = {fp} | FN = {fn} | TP = {tp}")

ConfusionMatrixDisplay(cm, display_labels=["No diabetes", "Diabetes"]).plot(cmap="Blues")
plt.title("Confusion Matrix")
plt.show()

RocCurveDisplay.from_predictions(y_test, y_prob)
plt.plot([0, 1], [0, 1], "k--", label="Random guess")
plt.title("ROC Curve")
plt.legend()
plt.show()

"""##Interpreting their coefficients"""

coef_df = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.named_steps["logreg"].coef_[0]
})
coef_df["Odds Ratio"] = np.exp(coef_df["Coefficient"])
coef_df = coef_df.sort_values("Coefficient", ascending=False)
display(coef_df.round(3))

plt.figure(figsize=(8, 5))
sns.barplot(x="Coefficient", y="Feature", data=coef_df)
plt.title("Logistic Regression Coefficients (standardized features)")
plt.show()