# -*- coding: utf-8 -*-
"""Mayank_L_Surana_Random_Forest_Project_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FjhA037gWZeaUboBFzi2tkcPeNSl_ZQ_

# Dataset Description

The Titanic dataset contains passenger information from the RMS Titanic, including demographic details, ticket class, fare, and survival status. It is used to build a classification model that predicts whether a passenger survived the disaster based on the available features.

##Importing the Libraries and Loading the Dataset
"""

import pandas as pd  #pandas for handling datasets
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files
uploaded = files.upload()

# Load the CSV file into a DataFrame
df = pd.read_csv("Titanic-Dataset.csv")

# Displaying a success message
print("Dataset loaded successfully!")

df.head()  #This is to display the first 5 rows of the uploaded file

"""## Exploring the Dataset Information and Data Types

"""

print("Dataset Shape:", df.shape) # Display dataset dimensions (rows and columns)

# Display column names, data types, and non-null counts
df.info()

# Display statistical summaries of numerical columns
df.describe()

"""## Checking for Missing Values

"""

# Count missing values in each column
print("Missing Values:")
print(df.isnull().sum())

"""##Data Preprocessing - Handling Missing Values

"""

# Check missing values in each column
print("Missing values before handling:")
print(df.isnull().sum())

# Fill missing Age values with the median
df["Age"] = df["Age"].fillna(df["Age"].median())

# Fill missing Embarked values with the mode
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

# Verify missing values after handling
print("\nMissing values after handling:")
print(df.isnull().sum())

"""##Analyzing the target class distribution"""

# Counting for each passengers in each survival category
print(df["Survived"].value_counts())

# Visualizing the distribution of the target variable
sns.countplot(data=df, x="Survived")

plt.title("Passenger Survival Distribution")
plt.xlabel("Survival Status (0 = Not Survived, 1 = Survived)")
plt.ylabel("Number of Passengers")
plt.show()

"""##Correlation Heatmap"""

# Selecting the numerical columns for correlation analysis
numeric_df = df.select_dtypes(include=["number"])

# Calculating the correlation between numerical variables
correlation = numeric_df.corr()

# Plotting the correlation heatmap
plt.figure(figsize=(10, 6))
sns.heatmap(correlation, annot=True, cmap="coolwarm", fmt=".2f")

plt.title("Correlation Heatmap of Numerical Features")
plt.show()

"""## Analyzing Survival Distribution by Gender

"""

# Displaying survival counts based on gender
print(pd.crosstab(df["Sex"], df["Survived"]))

# Visualizing survival distribution by gender
sns.countplot(data=df, x="Sex", hue="Survived")

plt.title("Survival Distribution by Gender")
plt.xlabel("Gender")
plt.ylabel("Number of Passengers")
plt.legend(title="Survival Status", labels=["Not Survived", "Survived"])
plt.show()

"""##Analyzing Survival Distribution by Passenger Class

"""

# Displaying survival counts across passenger classes
print(pd.crosstab(df["Pclass"], df["Survived"]))

# Visualizing survival distribution across passenger classes
sns.countplot(data=df, x="Pclass", hue="Survived")

plt.title("Survival Distribution by Passenger Class")
plt.xlabel("Passenger Class")
plt.ylabel("Number of Passengers")
plt.legend(title="Survival Status", labels=["Not Survived", "Survived"])
plt.show()

"""##Now Analyzing the Age Distribution of Passengers"""

# Visualizing the age distribution of passengers
plt.figure(figsize=(8, 5))

sns.histplot(data=df, x="Age", bins=30, kde=True)

plt.title("Age Distribution of Passengers")
plt.xlabel("Age")
plt.ylabel("Number of Passengers")

plt.show()

"""##Preparing the Dataset for Model Traini"""

print("Available Columns:", df.columns.tolist())

# Separating the target variable from the input features
X = df.drop(columns=["Survived"])
y = df["Survived"]

# Displaying the shapes of the input features and target variable
print("Input Features Shape:", X.shape)
print("Target Variable Shape:", y.shape)

"""##Encoding Categorical Features"""

categorical_columns = X.select_dtypes(include=["object"]).columns
X = pd.get_dummies(X, columns=categorical_columns, drop_first=True, dtype=int)

# Displaying the encoded dataset
print("Encoded Features:")
display(X.head())

# Displaying the updated dataset dimensions
print("Updated Feature Shape:", X.shape)

"""##Splitting the Dataset into Training and Testing Sets"""

# Importing the function for splitting the dataset
from sklearn.model_selection import train_test_split

# Splitting the dataset into 80% training data and 20% testing data
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=42, stratify=y)

print("Training Features Shape:", X_train.shape)
print("Testing Features Shape:", X_test.shape)
print("Training Target Shape:", y_train.shape)
print("Testing Target Shape:", y_test.shape)

"""##Building and Training the Random Forest Classifier"""

from sklearn.ensemble import RandomForestClassifier

# Initializing the Random Forest model with selected hyperparameters
rf_model = RandomForestClassifier(n_estimators=100,max_depth=10,random_state=42) #Using 100 decision trees to build the ensemble.

# Training the model using the training dataset
rf_model.fit(X_train, y_train)

# Displaying the model training confirmation
print("Random Forest model training completed successfully!")

"""##Confusion Matrix"""

# Generating predictions using the trained Random Forest model
y_pred = rf_model.predict(X_test)

# Importing the confusion matrix and its visualization tools
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
cm = confusion_matrix(y_test, y_pred)

# Visualizing the confusion matrix as a heatmap
plt.figure(figsize=(6, 4))
sns.heatmap(cm,annot=True,fmt="d",cmap="Blues",
    xticklabels=["Not Survived", "Survived"],
    yticklabels=["Not Survived", "Survived"])

plt.title("Confusion Matrix - Random Forest Classifier")
plt.xlabel("Predicted Class")
plt.ylabel("Actual Class")
plt.show()

"""##Evaluating Model Performance Using Precision, Recall, and F1-Score"""

# Importing classification evaluation metrics
from sklearn.metrics import precision_score, recall_score, f1_score, classification_report

precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Precision:", round(precision, 4))
print("Recall:", round(recall, 4))
print("F1-Score:", round(f1, 4))
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=["Not Survived", "Survived"]))

"""##Evaluating Model Performance Using the ROC-AUC Curve"""

from sklearn.metrics import roc_curve, roc_auc_score
y_prob = rf_model.predict_proba(X_test)[:, 1]
fpr, tpr, thresholds = roc_curve(y_test, y_prob)

# Calculating the ROC-AUC score
roc_auc = roc_auc_score(y_test, y_prob)

# Visualizing the ROC curve
plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, label=f"Random Forest (AUC = {roc_auc:.3f})")
plt.plot([0, 1], [0, 1], linestyle="--", label="Random Guessing")

plt.title("ROC-AUC Curve - Random Forest Classifier")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.legend()
plt.grid(True)
plt.show()

# Displaying the final ROC-AUC score
print("ROC-AUC Score:", round(roc_auc, 4))

"""##Now looking at the feature importance"""

feature_importance = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": rf_model.feature_importances_
})
feature_importance = feature_importance.sort_values(
    by="Importance", ascending=False
)

# Selecting the 10 most important features
top_features = feature_importance.head(10)

# Visualizing the 10 most important features
plt.figure(figsize=(10, 6))
sns.barplot(data=top_features, x="Importance", y="Feature")

plt.title("Top 10 Feature Importances - Random Forest Classifier")
plt.xlabel("Importance Score")
plt.ylabel("Feature")
plt.tight_layout()
plt.show()

# Displaying the feature importance rankings
display(top_features)

"""#CONCLUSION

###Evaluating passenger survival using ensemble learning.Analyzing classification performance through multiple metrics & Identifying influential features using feature importance.

"""